-- AlterTable
ALTER TABLE "User" ADD COLUMN     "usdBal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "usdLock" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "usdTotl" DOUBLE PRECISION NOT NULL DEFAULT 0;
